import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

import logo from "../public/luga.png";

const inter = Inter({ subsets: ["latin"] });
const rhyf: string =
  "https://media.licdn.com/dms/image/C5603AQFEDr3QdwqfNA/profile-displayphoto-shrink_800_800/0/1517375232641?e=2147483647&v=beta&t=g59GObJu5EVgPaFR5T--1NmA6Fp949oJRiaoIsCe8EU";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" border-b ">
          <div className=" max-w-[900px] mx-auto flex items-center justify-between p-4 ">
            <div className="  w-fit font-bold text-xl ">
              <Link href={"/"}>
                <Image
                  alt="luga"
                  className=" object-contain -ml-20  h-[30pt]"
                  src={logo}
                />
              </Link>
            </div>

            <div>My Account</div>
          </div>
        </div>
        <div className="p-4  max-w-[900px] mx-auto">{children}</div>
      </body>
    </html>
  );
}
